#!/usr/bin/perl

######################################################################################
# Script modified by Felix (http://skeena.net)
#
# Script by http://www.garyshood.com
# Requires the lib-www perl module
# Runs under mod_perl with no changes. 
# Validates under HTML 4.01 Transitional.
# This is licensed under the BSD license.
# 
# Copyright (c) 2007, Gary's Hood
# 
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 
# * Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation and/or 
# other materials provided with the distribution.
# * Neither the name of the Gary's Hood nor the names of its contributors 
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.                 
######################################################################################

#use HTML::Entities;
use CGI;
$query = new CGI;
print $query->header();
$self = $ENV{SCRIPT_NAME};
$perl = $ENV{DOCUMENT_ROOT};

print <<STARTHTML;

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>HTML To BB Code Converter</title>
</head>
<body>

STARTHTML

if ($query->param("html")) {
	$html = $query->param("html");
}

if (!$query->param("ascii")) {
	$html =~ s/\s\s+/\n/gi;
	$html =~ s/<pre(.*?)>(.*?)<\/pre>/\[code]$2\[\/code]/sgmi;
}
$html =~ s/<h[1-7](.*?)>(.*?)<\/h[1-7]>/\n\[b]$2\[\/b]\n/sgmi;

#paragraph handling:
#- if a paragraph opens on the same line as another one closes, insert an extra blank line
#- opening tag becomes two line breaks
#- closing tags are just removed
$html =~ s/<\/p><p/<\/p>\n<p/gi;
$html =~ s/<p[^>]*>/\n\n/gi;
$html =~ s/<\/p>//gi;

$html =~ s/<br(.*?)>/\n/gi;
$html =~ s/<textarea(.*?)>(.*?)<\/textarea>/\[code]$2\[\/code]/sgmi;
$html =~ s/<b>/[b]/gi;
$html =~ s/<i>/[i]/gi;
$html =~ s/<u>/[u]/gi;
$html =~ s/<\/b>/[\/b]/gi;
$html =~ s/<\/i>/[\/i]/gi;
$html =~ s/<\/u>/[\/u]/gi;
$html =~ s/<em>/[b]/gi;
$html =~ s/<\/em>/[\/b]/gi;
$html =~ s/<strong>/[b]/gi;
$html =~ s/<\/strong>/[\/b]/gi;
$html =~ s/<cite>/[i]/gi;
$html =~ s/<\/cite>/[\/i]/gi;
$html =~ s/<font color="(.*?)">(.*?)<\/font>/\[color=$1]$2\[\/color]/sgmi;
$html =~ s/<font color=(.*?)>(.*?)<\/font>/\[color=$1]$2\[\/color]/sgmi;
$html =~ s/<link(.*?)>//gi;
$html =~ s/<li(.*?)>(.*?)<\/li>/\[\*]$2/gi;
$html =~ s/<ul(.*?)>/\[list]/gi;
$html =~ s/<\/ul>/\[\/list]/gi;
$html =~ s/<div>/\n/gi;
$html =~ s/<\/div>/\n/gi;
$html =~ s/<td(.*?)>/ /gi;
$html =~ s/<tr(.*?)>/\n/gi;

$html =~ s/<img(.*?)src="(.*?)"(.*?)>/\[img]$2\[\/img]/gi;
$html =~ s/<a(.*?)href="(.*?)"(.*?)>(.*?)<\/a>/\[url=$2]$4\[\/url]/gi;

$html =~ s/<head>(.*?)<\/head>//sgmi;
$html =~ s/<object>(.*?)<\/object>//sgmi;
$html =~ s/<script(.*?)>(.*?)<\/script>//sgmi;
$html =~ s/<style(.*?)>(.*?)<\/style>//sgmi;
$html =~ s/<title>(.*?)<\/title>//sgmi;
$html =~ s/<!--(.*?)-->/\n/sgmi;

$html =~ s/\/\//\//gi;
$html =~ s/http:\//http:\/\//gi;

$html =~ s/<(?:[^>'"]*|(['"]).*?\1)*>//gsi;
$html =~ s/\r\r//gi;
$html =~ s/\[img]\//\[img]/gi;
$html =~ s/\[url=\//\[url=/gi;

$html =~ s/(\S)\n/$1 /gi;

if(!defined($html)) {
	$html = "";
}

print <<MOREHTML;

<h2>HTML To BB Code Converter</h2>

<div class="right">
<p>The Perl code behind this page was adapted from <a
href="http://www.garyshood.com/htmltobb/">http://www.garyshood.com/htmltobb/</a>.
The modified <a href="htmltobb-felix.bz2">source is here</a>.<br>
(I changed it to handle a few things a little better, mostly paragraph breaks and newlines.)</p>
</div>

<h3>Usage</h3>
<p>
This is a form that will convert basic HTML into BB code that is used on various forums. It will strip out most HTML that cannot
be converted. 
</p>

<form method="post" action="$self">
<p><input type="checkbox" name="ascii">Check this for ASCII Art</p>

HTML:<br>
<textarea cols="115" rows="25" name="html">$html</textarea>
<p><input type="submit" value="Submit HTML"></p>
</form>
</body>
</html>

MOREHTML

undef $html;
